In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
Pluto_2009 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\MN09V2.txt", dtype={"Tract2000": str})
Pluto_2010 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\mn10v2.txt", dtype={"Tract2000": str})
Pluto_2011 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\mn11v2.txt", dtype={"Tract2010": str})
Pluto_2012 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\mn12v2.txt", dtype={"Tract2010": str})
Pluto_2013 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\MN_2013.csv", dtype={"Tract2010": str})
Pluto_2014 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\MN_2014.csv", dtype={"Tract2010": str})
Pluto_2015 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\MN_2015.csv", dtype={"Tract2010": str})
Pluto_2016 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\MN_2016.csv", dtype={"Tract2010": str})
Pluto_2017 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\MN_2017.csv", dtype={"Tract2010": str})

C:\Users\fiodo\AppData\Local\Temp\ipykernel_21380\1370901825.py:2: DtypeWarning: Columns (75) have mixed types. Specify dtype option on import or set low_memory=False.
  Pluto_2010 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\mn10v2.txt", dtype={"Tract2000": str})
C:\Users\fiodo\AppData\Local\Temp\ipykernel_21380\1370901825.py:3: DtypeWarning: Columns (76) have mixed types. Specify dtype option on import or set low_memory=False.
  Pluto_2011 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\mn11v2.txt", dtype={"Tract2010": str})
C:\Users\fiodo\AppData\Local\Temp\ipykernel_21380\1370901825.py:4: DtypeWarning: Columns (74) have mixed types. Specify dtype option on import or set low_memory=False.
  Pluto_2012 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\mn12v2.txt", dtype={"Tract2010": str})
C:\Users\fiodo\AppData\Local\Temp\ipykernel_21380\1370901825.py:5: DtypeWarning: Columns (15,18,19,20,77) have mixed types. Specify dtype option on import or set low_memory=False.
  Pluto_2013 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\MN_2013.csv", dtype={"Tract2010": str})
C:\Users\fiodo\AppData\Local\Temp\ipykernel_21380\1370901825.py:6: DtypeWarning: Columns (16,19,20,21,78) have mixed types. Specify dtype option on import or set low_memory=False.
  Pluto_2014 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\MN_2014.csv", dtype={"Tract2010": str})
C:\Users\fiodo\AppData\Local\Temp\ipykernel_21380\1370901825.py:8: DtypeWarning: Columns (19,22,23,25,63,79) have mixed types. Specify dtype option on import or set low_memory=False.
  Pluto_2016 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\MN_2016.csv", dtype={"Tract2010": str})
C:\Users\fiodo\AppData\Local\Temp\ipykernel_21380\1370901825.py:9: DtypeWarning: Columns (19,20,22,24,26) have mixed types. Specify dtype option on import or set low_memory=False.
  Pluto_2017 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\MN_2017.csv", dtype={"Tract2010": str})

In [3]:
Pluto_2018 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\pluto_18v2_1.csv",dtype={"tract2010": str})
Pluto_2019 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\pluto_19v2.csv",dtype={"tract2010": str} )
Pluto_2020 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\pluto_20v8.csv",dtype={"tract2010": str} )

C:\Users\fiodo\AppData\Local\Temp\ipykernel_21380\765814571.py:1: DtypeWarning: Columns (16,17,18,20,22,77) have mixed types. Specify dtype option on import or set low_memory=False.
  Pluto_2018 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\pluto_18v2_1.csv",dtype={"tract2010": str})
C:\Users\fiodo\AppData\Local\Temp\ipykernel_21380\765814571.py:2: DtypeWarning: Columns (17,18,20,22,24,62,96) have mixed types. Specify dtype option on import or set low_memory=False.
  Pluto_2019 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\pluto_19v2.csv",dtype={"tract2010": str} )
C:\Users\fiodo\AppData\Local\Temp\ipykernel_21380\765814571.py:3: DtypeWarning: Columns (18,19,20,21,22,23,24,26,63,76,79,86) have mixed types. Specify dtype option on import or set low_memory=False.
  Pluto_2020 = pd.read_csv("D:\LMU_Life\Housing\project\PLUTO Data\pluto_20v8.csv",dtype={"tract2010": str} )

In [4]:
def normalize_tract6(val):
    if pd.isna(val):
        return None
    val = val.strip().zfill(4)  # ensures at least 4 digits
    return val.ljust(6, "0")    # pad right side to total 6 digits

In [5]:
Pluto_2009["Tract2000"] = Pluto_2009["Tract2000"].apply(normalize_tract6)
Pluto_2010["Tract2000"] = Pluto_2010["Tract2000"].apply(normalize_tract6)
Pluto_2011["Tract2010"] = Pluto_2011["Tract2010"].apply(normalize_tract6)
Pluto_2012["Tract2010"] = Pluto_2012["Tract2010"].apply(normalize_tract6)
Pluto_2013["Tract2010"] = Pluto_2013["Tract2010"].apply(normalize_tract6)
Pluto_2014["Tract2010"] = Pluto_2014["Tract2010"].apply(normalize_tract6)
Pluto_2015["Tract2010"] = Pluto_2015["Tract2010"].apply(normalize_tract6)
Pluto_2016["Tract2010"] = Pluto_2016["Tract2010"].apply(normalize_tract6)
Pluto_2017["Tract2010"] = Pluto_2017["Tract2010"].apply(normalize_tract6)
Pluto_2018["tract2010"] = Pluto_2018["tract2010"].apply(normalize_tract6)
Pluto_2019["tract2010"] = Pluto_2019["tract2010"].apply(normalize_tract6)
Pluto_2020["tract2010"] = Pluto_2020["tract2010"].apply(normalize_tract6)

In [6]:
Pluto_2018_MN = Pluto_2018[Pluto_2018['borough'] == 'MN']
Pluto_2019_MN = Pluto_2019[Pluto_2019['borough'] == 'MN']
Pluto_2020_MN = Pluto_2020[Pluto_2020['borough'] == 'MN']

In [7]:
def full_tract(df, tract_col, borough_num):

    df['full_tract'] = np.where(
        df[tract_col].notna(),
        "36" + borough_num + df[tract_col].astype(str).str.zfill(6),
        np.nan
    )

    return df

In [8]:
Pluto_2009=full_tract(Pluto_2009, 'Tract2000', '061')
Pluto_2009

,Borough,Block,Lot,CD,CT2000,CB2000,SchoolDist,Council,ZipCode,FireComp,...,DCASDate,ZoningDate,MajPrpDate,LandmkDate,DTMDate,MASDate,PoliDate,EDesigDate,PLUTOMapID,full_tract
0,MN,1.0,10.0,101.0,5,1020,02,01,10004,E007,...,8/2009,9/2009,8/2009,9/2009,9/2009,6/2009,6/2009,7/2009,1.0,36061000500
1,MN,1.0,101.0,101.0,1,9000,02,01,10004,,...,8/2009,9/2009,8/2009,9/2009,9/2009,6/2009,6/2009,7/2009,1.0,36061000100
2,MN,1.0,201.0,101.0,1,1000,02,01,10004,,...,8/2009,9/2009,8/2009,9/2009,9/2009,6/2009,6/2009,7/2009,1.0,36061000100
3,MN,2.0,1.0,101.0,9,2012,02,01,10004,L015,...,8/2009,9/2009,8/2009,9/2009,9/2009,6/2009,6/2009,7/2009,1.0,36061000900
4,MN,2.0,23.0,101.0,319,9015,02,01,10004,L015,...,8/2009,9/2009,8/2009,9/2009,9/2009,6/2009,6/2009,7/2009,1.0,36061031900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43835,MN,2250.0,158.0,112.0,307,2001,06,07,10034,E095,...,8/2009,9/2009,8/2009,9/2009,9/2009,6/2009,6/2009,7/2009,1.0,36061030700
43836,MN,2255.0,1.0,112.0,297,1000,06,07,10034,E095,...,8/2009,9/2009,8/2009,9/2009,9/2009,6/2009,6/2009,7/2009,1.0,36061029700
43837,MN,2255.0,1031.0,112.0,297,,06,07,10034,E095,...,8/2009,9/2009,8/2009,9/2009,9/2009,6/2009,6/2009,7/2009,1.0,36061029700
43838,MN,2255.0,2000.0,112.0,297,1000,06,07,10034,E095,...,8/2009,9/2009,8/2009,9/2009,9/2009,6/2009,6/2009,7/2009,1.0,36061029700
43839,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
Pluto_2009=full_tract(Pluto_2009, 'Tract2000', '061')
Pluto_2010=full_tract(Pluto_2010, 'Tract2000', '061')
Pluto_2011=full_tract(Pluto_2011, 'Tract2010', '061')
Pluto_2012=full_tract(Pluto_2012, 'Tract2010', '061')
Pluto_2013=full_tract(Pluto_2013, 'Tract2010', '061')
Pluto_2014=full_tract(Pluto_2014, 'Tract2010', '061')
Pluto_2015=full_tract(Pluto_2015, 'Tract2010', '061')
Pluto_2016=full_tract(Pluto_2016, 'Tract2010', '061')
Pluto_2017=full_tract(Pluto_2017, 'Tract2010', '061')
Pluto_2018_MN=full_tract(Pluto_2018_MN, 'tract2010', '061')
Pluto_2019_MN=full_tract(Pluto_2019_MN, 'tract2010', '061')
Pluto_2020_MN=full_tract(Pluto_2020_MN, 'tract2010', '061')

C:\Users\fiodo\AppData\Local\Temp\ipykernel_21380\3349246032.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['full_tract'] = np.where(
C:\Users\fiodo\AppData\Local\Temp\ipykernel_21380\3349246032.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['full_tract'] = np.where(
C:\Users\fiodo\AppData\Local\Temp\ipykernel_21380\3349246032.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['full_tract'] = np.where(

In [12]:
Pluto_2009.to_csv("D:\LMU_Life\Housing\project\PLUTO Data\clean_MN\PLUTO_MN_2009.csv", index=False)
Pluto_2010.to_csv("D:\LMU_Life\Housing\project\PLUTO Data\clean_MN\PLUTO_MN_2010.csv", index=False)
Pluto_2011.to_csv("D:\LMU_Life\Housing\project\PLUTO Data\clean_MN\PLUTO_MN_2011.csv", index=False)
Pluto_2012.to_csv("D:\LMU_Life\Housing\project\PLUTO Data\clean_MN\PLUTO_MN_2012.csv", index=False)
Pluto_2013.to_csv("D:\LMU_Life\Housing\project\PLUTO Data\clean_MN\PLUTO_MN_2013.csv", index=False)
Pluto_2014.to_csv("D:\LMU_Life\Housing\project\PLUTO Data\clean_MN\PLUTO_MN_2014.csv", index=False)
Pluto_2015.to_csv("D:\LMU_Life\Housing\project\PLUTO Data\clean_MN\PLUTO_MN_2015.csv", index=False)
Pluto_2016.to_csv("D:\LMU_Life\Housing\project\PLUTO Data\clean_MN\PLUTO_MN_2016.csv", index=False)
Pluto_2017.to_csv("D:\LMU_Life\Housing\project\PLUTO Data\clean_MN\PLUTO_MN_2017.csv", index=False)
Pluto_2018_MN.to_csv("D:\LMU_Life\Housing\project\PLUTO Data\clean_MN\PLUTO_MN_2018.csv", index=False)
Pluto_2019_MN.to_csv("D:\LMU_Life\Housing\project\PLUTO Data\clean_MN\PLUTO_MN_2019.csv", index=False)
Pluto_2020_MN.to_csv("D:\LMU_Life\Housing\project\PLUTO Data\clean_MN\PLUTO_MN_2020.csv", index=False)

Aggregate up to tract level

In [10]:
Pluto_2009['year']=2009
Pluto_2010['year']=2010
Pluto_2011['year']=2011
Pluto_2012['year']=2012
Pluto_2013['year']=2013
Pluto_2014['year']=2014
Pluto_2015['year']=2015
Pluto_2016['year']=2016
Pluto_2017['year']=2017
Pluto_2018_MN['year']=2018
Pluto_2019_MN['year']=2019
Pluto_2020_MN['year']=2020

C:\Users\fiodo\AppData\Local\Temp\ipykernel_21380\3285374865.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Pluto_2018_MN['year']=2018
C:\Users\fiodo\AppData\Local\Temp\ipykernel_21380\3285374865.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Pluto_2019_MN['year']=2019
C:\Users\fiodo\AppData\Local\Temp\ipykernel_21380\3285374865.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Pluto_2020_MN['year']=2020

In [11]:
def Pluto_agg(df):
    df_agg = (
        df
        .groupby(['full_tract', 'year'])[
            ['LotArea', 'BldgArea', 'ComArea', 'ResArea', 'OfficeArea',
             'RetailArea', 'GarageArea', 'StrgeArea', 'FactryArea',
             'OtherArea', 'NumBldgs', 'NumFloors', 'UnitsRes', 'UnitsTotal', 
             'AssessLand', 'AssessTot']
        ]
        .agg('sum')
        .reset_index()
    )
    df_agg.columns = df_agg.columns.str.lower()
    return df_agg

In [12]:
Pluto_2009_agg=Pluto_agg(Pluto_2009)
Pluto_2010_agg=Pluto_agg(Pluto_2010)
Pluto_2011_agg=Pluto_agg(Pluto_2011)
Pluto_2012_agg=Pluto_agg(Pluto_2012)
Pluto_2013_agg=Pluto_agg(Pluto_2013)
Pluto_2014_agg=Pluto_agg(Pluto_2014)
Pluto_2015_agg=Pluto_agg(Pluto_2015)
Pluto_2016_agg=Pluto_agg(Pluto_2016)
Pluto_2017_agg=Pluto_agg(Pluto_2017)

In [13]:
def Pluto_agg_2018_2020(df):

    df_agg=(df
                .groupby(['full_tract', 'year'])
                [['lotarea', 'bldgarea', 'comarea', 'resarea', 'officearea',
                    'retailarea', 'garagearea', 'strgearea', 'factryarea',
                'otherarea', 'numbldgs', 'numfloors', 'unitsres', 'unitstotal',
                'assessland', 'assesstot']]
                 .agg('sum')
                 .reset_index())
    return df_agg

In [14]:
Pluto_2018_agg=Pluto_agg_2018_2020(Pluto_2018_MN)
Pluto_2019_agg=Pluto_agg_2018_2020(Pluto_2019_MN)
Pluto_2020_agg=Pluto_agg_2018_2020(Pluto_2020_MN)

In [15]:
pluto_agg_MN_all_years = pd.concat([
    Pluto_2009_agg, Pluto_2010_agg, Pluto_2011_agg,
    Pluto_2012_agg, Pluto_2013_agg, Pluto_2014_agg,
    Pluto_2015_agg, Pluto_2016_agg, Pluto_2017_agg,
    Pluto_2018_agg, Pluto_2019_agg, Pluto_2020_agg
])
pluto_agg_MN_all_years = pluto_agg_MN_all_years.sort_values(by=['full_tract', 'year'])
pluto_agg_MN_all_years

,full_tract,year,lotarea,bldgarea,comarea,resarea,officearea,retailarea,garagearea,strgearea,factryarea,otherarea,numbldgs,numfloors,unitsres,unitstotal,assessland,assesstot
0,36061000000,2009,21887429.0,131917.0,131917.0,0.0,50000.0,0.0,0.0,0.0,0.0,81917.0,10.0,7.0,0.0,6.0,364595131.0,429903041.0
0,36061000000,2010,9180612.0,221319.0,208259.0,13060.0,52175.0,1563.0,0.0,0.0,0.0,154521.0,10.0,7.0,0.0,6.0,375233226.0,385718446.0
0,36061000000,2011,14879829.0,1053266.0,630607.0,422659.0,56168.0,1563.0,214320.0,0.0,0.0,358556.0,13.0,48.0,394.0,404.0,425187000.0,475249720.0
0,36061000000,2012,25840040.0,1172171.0,792553.0,379618.0,56168.0,1563.0,298020.0,0.0,0.0,436802.0,12.0,42.0,370.0,380.0,413086142.0,524401087.0
0,36061000000,2013,25517959.0,698214.0,698214.0,0.0,50000.0,1563.0,298020.0,0.0,0.0,348631.0,9.0,11.0,0.0,7.0,411887412.0,496931312.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,36061860300,2013,817270.0,6231156.0,972882.0,5258274.0,389778.0,92285.0,205873.0,39092.0,0.0,245854.0,93.0,786.0,3837.0,4004.0,142341312.0,568092168.0
288,36061860300,2014,817270.0,6083901.0,829327.0,5254574.0,398478.0,96030.0,205873.0,34092.0,0.0,94854.0,93.0,780.0,4017.0,4184.0,139374231.0,593005480.0
288,36061860300,2015,817270.0,6070195.0,815621.0,5254574.0,398478.0,96030.0,192167.0,34092.0,0.0,94854.0,93.0,780.0,4015.0,4185.0,139836081.0,655220986.0
288,36061860300,2017,905627.0,6116900.0,728704.0,5233307.0,306543.0,103614.0,190975.0,32718.0,0.0,94854.0,93.0,780.0,4017.0,4285.0,139803123.0,715325332.0
287,36061860300,2018,817277.0,6096673.0,721803.0,5232490.0,299642.0,103614.0,190975.0,32718.0,0.0,94854.0,93.0,780.0,4018.0,4205.0,140051792.0,731411810.0

In [56]:
pluto_agg_MN_all_years.dtypes

full_tract     object
year            int64
lotarea       float64
bldgarea      float64
comarea       float64
resarea       float64
officearea    float64
retailarea    float64
garagearea    float64
strgearea     float64
factryarea    float64
otherarea     float64
numbldgs      float64
numfloors     float64
unitsres      float64
unitstotal    float64
dtype: object

In [16]:
pluto_agg_MN_all_years.to_csv("D:\LMU_Life\Housing\project\PLUTO Data\clean_MN\pluto_agg_MN_all_years.csv", index=False)

In [17]:
pluto_agg_MN_all_years

,full_tract,year,lotarea,bldgarea,comarea,resarea,officearea,retailarea,garagearea,strgearea,factryarea,otherarea,numbldgs,numfloors,unitsres,unitstotal,assessland,assesstot
0,36061000000,2009,21887429.0,131917.0,131917.0,0.0,50000.0,0.0,0.0,0.0,0.0,81917.0,10.0,7.0,0.0,6.0,364595131.0,429903041.0
0,36061000000,2010,9180612.0,221319.0,208259.0,13060.0,52175.0,1563.0,0.0,0.0,0.0,154521.0,10.0,7.0,0.0,6.0,375233226.0,385718446.0
0,36061000000,2011,14879829.0,1053266.0,630607.0,422659.0,56168.0,1563.0,214320.0,0.0,0.0,358556.0,13.0,48.0,394.0,404.0,425187000.0,475249720.0
0,36061000000,2012,25840040.0,1172171.0,792553.0,379618.0,56168.0,1563.0,298020.0,0.0,0.0,436802.0,12.0,42.0,370.0,380.0,413086142.0,524401087.0
0,36061000000,2013,25517959.0,698214.0,698214.0,0.0,50000.0,1563.0,298020.0,0.0,0.0,348631.0,9.0,11.0,0.0,7.0,411887412.0,496931312.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,36061860300,2013,817270.0,6231156.0,972882.0,5258274.0,389778.0,92285.0,205873.0,39092.0,0.0,245854.0,93.0,786.0,3837.0,4004.0,142341312.0,568092168.0
288,36061860300,2014,817270.0,6083901.0,829327.0,5254574.0,398478.0,96030.0,205873.0,34092.0,0.0,94854.0,93.0,780.0,4017.0,4184.0,139374231.0,593005480.0
288,36061860300,2015,817270.0,6070195.0,815621.0,5254574.0,398478.0,96030.0,192167.0,34092.0,0.0,94854.0,93.0,780.0,4015.0,4185.0,139836081.0,655220986.0
288,36061860300,2017,905627.0,6116900.0,728704.0,5233307.0,306543.0,103614.0,190975.0,32718.0,0.0,94854.0,93.0,780.0,4017.0,4285.0,139803123.0,715325332.0
287,36061860300,2018,817277.0,6096673.0,721803.0,5232490.0,299642.0,103614.0,190975.0,32718.0,0.0,94854.0,93.0,780.0,4018.0,4205.0,140051792.0,731411810.0

In [18]:
tract='36061009900'


df_filtered = pluto_agg_MN_all_years[pluto_agg_MN_all_years['full_tract'] == tract ]
# Select all columns except 'year'
y_cols = df_filtered.columns.drop(['year','full_tract'])
# Aggregate the data by 'year', summing up the Flow_to_work and Flow_to_home for each year
df_aggregated = df_filtered.groupby('year')[y_cols].sum().reset_index()

# Create the time series plot
fig = px.line(df_aggregated, 
              x='year', 
              y=y_cols,
              title=f"buildings in {tract}", 
              labels={'year': 'Year', 'value': 'Flow Value'}, 
              line_shape='linear')

special_year = 2015  

# Add a vertical line at the special year
fig.add_vline(
    x=special_year,
    line_width=2,
    line_dash="dash",
    line_color="red",
    annotation_text="subway open",  # Optional text annotation
    annotation_position="top"  # Optional position for the annotation
)

# Show the plot
fig.show()